---
trainer:
  accelerator: gpu
  max_epochs: 3
  limit_train_batches: 1000
  limit_val_batches: 100
  log_every_n_steps: 5
  num_sanity_val_steps: 0
  gradient_clip_val: 5
training:
  loss: l1_loss
  parameter_space:
    - name: learning_rate
      type: fixed
      value: 0.00005
      # type: range
      # bounds:
        # - 0.000001
        # - 0.01
      # log_scale: true
    - name: weight_decay
      type: fixed
      value: 0
      # type: range
      # bounds:
        # - 0.000001
        # - 0.01
      log_scale: true
    - name: batch_size
      type: fixed
      value: 128
      # type: range
      # bounds:
        # - 16
        # - 128


  validation_split: 0.2
  scaling: false


benchmarks:
  # binomial_options:
  #     model:
  #       architecture:
  #         - Linear:
  #             args: [5, 128]
  #         - BatchNorm1d:
  #             args: [128]
  #         - ReLU:
  #             inplace: true
  #         - Linear:
  #             args: [128, 128]
  #         - BatchNorm1d:
  #             args: [128]
  #         - ReLU:
  #             inplace: true
  #         - Linear:
  #             args: [128, 128]
  #         - BatchNorm1d:
  #             args: [128]
  #         - ReLU:
  #             inplace: true
  #         - Linear:
  #             args: [128, 128]
  #         - BatchNorm1d:
  #             args: [128]
  #         - ReLU:
  #             inplace: true
  #         - Linear:
  #             args: [128, 128]
  #         - BatchNorm1d:
  #             args: [128]
  #         - ReLU:
  #             inplace: true
  #         - Linear:
  #             args: [128, 128]
  #         - BatchNorm1d:
  #             args: [128]
  #         - ReLU:
  #             inplace: true
  #         - Linear:
  #             args: [128, 1]

  #     datasets:
  #       tails_id:
  #         format: hdf5
  #         path: '/scratch/mzu/zanef2/surrogates/training_data/bude_bm2long_65536_train.h5'
  #         group_name: BinomialOptionsKernel
  #         input_dataset: input
  #         output_dataset: output
  #         percentiles: '[0, 70]'
  #       tails_ood:
  #         format: hdf5
  #         path: '/scratch/mzu/zanef2/surrogates/training_data/bude_bm2long_65536_train.h5'
  #         group_name: BinomialOptionsKernel
  #         input_dataset: input
  #         output_dataset: output
  #         percentiles: '[70, 100]'
  #       gaps_id:
  #         format: hdf5
  #         path: '/scratch/mzu/zanef2/surrogates/training_data/bude_bm2long_65536_train.h5'
  #         group_name: BinomialOptionsKernel
  #         input_dataset: input
  #         output_dataset: output
  #         percentiles: '[0, 30], [60, 100]'
  #       gaps_ood:
  #         format: hdf5
  #         path: '/scratch/mzu/zanef2/surrogates/training_data/bude_bm2long_65536_train.h5'
  #         group_name: BinomialOptionsKernel
  #         input_dataset: input
  #         output_dataset: output
  #         percentiles: '[30, 60]'

  minibude:
     model:
       architecture:
         - Linear:
             args: [6, 128]
         - BatchNorm1d:
             args: [128]
         - ReLU:
             inplace: true
         - Linear:
             args: [128, 128]
         - BatchNorm1d:
             args: [128]
         - ReLU:
             inplace: true
         - Linear:
             args: [128, 128]
         - BatchNorm1d:
             args: [128]
         - ReLU:
             inplace: true
         - Linear:
             args: [128, 128]
         - BatchNorm1d:
             args: [128]
         - ReLU:
             inplace: true
         - Linear:
             args: [128, 128]
         - BatchNorm1d:
             args: [128]
         - ReLU:
             inplace: true
         - Linear:
             args: [128, 128]
         - BatchNorm1d:
             args: [128]
         - ReLU:
             inplace: true
         - Linear:
             args: [128, 1]

     datasets:
       tails_id:
         format: hdf5
         path: /projects/mzu/training_data/bude_bm2long_65536_train.h5
         group_name: BUDEKernel
         input_dataset: input
         output_dataset: output
         percentiles: '[0, 70]'
       tails_ood:
         format: hdf5
         path: /projects/mzu/training_data/bude_bm2long_65536_train.h5
         group_name: BUDEKernel
         input_dataset: input
         output_dataset: output
         percentiles: '[70, 100]'
       gaps_id:
         format: hdf5
         path: /projects/mzu/training_data/bude_bm2long_65536_train.h5
         group_name: BUDEKernel
         input_dataset: input
         output_dataset: output
         percentiles: '[0, 30], [60, 100]'
       gaps_ood:
         format: hdf5
         path: /projects/mzu/training_data/bude_bm2long_65536_train.h5
         group_name: BUDEKernel
         input_dataset: input
         output_dataset: output
         percentiles: '[30, 60]'


  ailerons:
    model:
      architecture:
        - Linear:
            args: [40, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 1]

    datasets:
      tails_id:
        format: arff
        path: /projects/mzu/training_data/ailerons.arff
        percentiles: '[0, 70]'
      tails_ood:
        format: arff
        path: /projects/mzu/training_data/ailerons.arff
        percentiles: '[70, 100]'

      gaps_id:
        format: arff
        path: /projects/mzu/training_data/ailerons.arff
        percentiles: '[0, 30], [60, 100]'
      gaps_ood:
        format: arff
        path: /projects/mzu/training_data/ailerons.arff
        percentiles: '[30, 60]'


  airfoil:
    model:
      architecture:
        - Linear:
            args: [5, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 1]

    datasets:
      tails_id:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/airfoil_self_noise.dat
        percentiles: '[0, 70]'
      tails_ood:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/airfoil_self_noise.dat
        percentiles: '[70, 100]'
      gaps_id:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/airfoil_self_noise.dat
        percentiles: '[0, 30], [60, 100]'
        dtype: float32
      gaps_ood:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/airfoil_self_noise.dat
        percentiles: '[30, 60]'
        dtype: float32


  puma:
    model:
      architecture:
        - Linear:
            args: [8, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 128]
        - BatchNorm1d:
            args: [128]
        - ReLU:
            inplace: true
        - Linear:
            args: [128, 1]

    datasets:
      tails_id:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/pumadyn-8fm/Dataset.data
        percentiles: '[0, 70]'
      tails_ood:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/pumadyn-8fm/Dataset.data
        percentiles: '[70, 100]'
      gaps_id:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/pumadyn-8fm/Dataset.data
        percentiles: '[0, 30], [60, 100]'
      gaps_ood:
        format: character_delimited
        delimiter: '\s+'
        path: /projects/mzu/training_data/pumadyn-8fm/Dataset.data
        percentiles: '[30, 60]'



uq_methods:
    kde:
      parameter_space:
        - name: bandwidth
          type: choice
          values:
            - 'scott'
            - 'silverman'
        - name: rtol
          type: range
          # for some reason, ax doesn't suggest very diverse values when
          # we give a range like 0.05, 0.5.
          # We'll do this instead and convert in the impl.
          bounds:
            - 500
            - 50000
    knn_kde:
      parameter_space:
        - name: k
          type: range
          bounds:
            - 1
            - 800
        - name: bandwidth
          type: fixed
          value: 'scott'

bo_config:
  trials: 50
  max_failures: 10
  evaluation_metric: 
    - name: percentile_score
      percentile: 95
    - name: uncertainty_estimating_throughput

evaluation:
  metrics:
    - name: tnr_at_tpr
      target_tpr: 0.95
      reversed: false
    - name: percentile_classification
      threshold: 0.90
      reversed: false
    - name: percentile_classification
      threshold: 0.90
      reversed: true
    - name: percentile_classification
      threshold: 0.80
      reversed: true
    - name: percentile_classification
      threshold: 0.80
      reversed: false
    - name: runtime
    - name: uncertainty_estimating_runtime
    - name: base_model_throughput
    - name: auroc
    - name: uncertainty_estimating_throughput
    - name: max_memory_usage

bo_slurm_config:
  partition: "gpuA40x4-preempt"
  account: "mzu-delta-gpu"
  gpus_per_task: 1
  cpus_per_gpu: 16
  nodes: 1
  ntasks_per_node: 1
  nodes_per_block: 1
  max_blocks: 3
  init_blocks: 1
  parallelism: 1
  exclusive: false
  mem_per_node: 64
  walltime: "1:55:00"
  cmd_timeout: 120

metric_eval_slurm_config:
  partition: "gpuA100x4"
  account: "mzu-delta-gpu"
  gpus_per_task: 1
  cpus_per_gpu: 16
  nodes: 1
  ntasks_per_node: 1
  nodes_per_block: 1
  max_blocks: 3
  init_blocks: 1
  parallelism: 1
  exclusive: false
  mem_per_node: 64
  walltime: "00:35:00"
  cmd_timeout: 120