---
models:
  resnet_50_size:
    architecture:
      - Linear:
          args: [4, 2048]
      - BatchNorm1d:
          args: [2048]
      - ReLU:
          inplace: true
      - Repeat:
          count: 6
          layers:
            - Linear:
                args: [2048, 2048]
            - BatchNorm1d:
                args: [2048]
            - ReLU:
                inplace: true
      - Linear:
          args: [2048, 1]
  
  resnet_101_size:
    architecture:
      - Linear:
          args: [4, 2048]
      - BatchNorm1d:
          args: [2048]
      - ReLU:
          inplace: true
      - Repeat:
          count: 11
          layers:
            - Linear:
                args: [2048, 2048]
            - BatchNorm1d:
                args: [2048]
            - ReLU:
                inplace: true
      - Linear:
          args: [2048, 1]

dataset:
  five_d_uniform_id:
    format: numpy
    path: dataset.npy
    subset:
      start: 0
      stop: 1024

uq_methods:
  ensemble:
    parameter_space:
      - name: num_models
        type: range
        bounds:
          - 2
          - 32
  delta_uq:
    parameter_space:
      - name: num_anchors
        type: range
        bounds:
          - 5
          - 500
      - name: anchored_batch_size
        type: range
        bounds:
          - 64
          - 1024
        log_scale: true
      - name: estimator
        type: fixed
        value: 'std'
  pager:
    parameter_space:
      - name: num_anchors
        type: range
        bounds:
          - 5
          - 300
      - name: anchored_batch_size
        type: range
        bounds:
          - 64
          - 1024
        log_scale: true
      - name: estimator
        type: fixed
        value: 'std'
  mc_dropout:
    parameter_space:
      - name: num_samples
        type: range
        bounds:
          - 2
          - 32
      - name: dropout_percent
        type: range
        bounds: 
          - 0.05
          - 0.3
  deep_evidential:
    parameter_space:
      - name: lam
        type: range
        bounds:
          - 0.00001
          - 0.1
        log_scale: true
  kde:
    parameter_space:
      - name: bandwidth
        type: range
        bounds:
          - 0.001
          - 10.0
        log_scale: true
      - name: rtol
        type: range
        bounds:
          - 0.0001
          - 0.1
        log_scale: true
  knn_kde:
    parameter_space:
      - name: k
        type: range
        bounds:
          - 5
          - 32
      - name: bandwidth
        type: range
        bounds:
          - 0.001
          - 10.0
        log_scale: true
  no_uq:
     parameter_space: []
     uncertainty_value: 1.0

run_config:
  max_runs_per_method: 100
evaluation:
  metrics:
    - name: uncertainty_estimating_throughput
    - name: max_memory_usage

throughput_slurm_config:
  partition: "gpuA100x4-preempt"
  account: "mzu-delta-gpu"
  gpus_per_task: 1
  cpus_per_gpu: 16
  nodes: 1
  ntasks_per_node: 1
  nodes_per_block: 1
  max_blocks: 10
  init_blocks: 1
  parallelism: 1
  exclusive: false
  mem_per_node: 64
  walltime: "00:15:00"
  cmd_timeout: 120
